spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.VoidSerializer
spring.kafka.producer.value-serializer=ru.yandex.practicum.CollectorSerializer